#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

"$RUN_PATH/build_image" &&
    docker run -it --rm --network host \
        -v "$KUBE_CONFIG:/home/airflow/.kube/config" \
        -v "$DAGS_PATH:/opt/airflow/dags" "$IMAGE_TAG"
