#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "----------------------"
    echo "Running python version:"
    python --version
    echo "----------------------"
    echo "Running airflow version:"
    airflow version
    echo "----------------------"
    airflow db init || exit $?
    echo "----------------------"
    echo "Init complete. Starting airflow"
    echo "----------------------"
    airflow webserver &
    WEBSERVER_PID="$!"
    echo "Started webserver"
    airflow scheduler &
    SCHEDULER_PID="$!"
    echo "Started scheduler"
    wait "$SCHEDULER_PID"
    kill "$WEBSERVER_PID"
else
    airflow "$@"
fi
