#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "----------------------"
    echo "Running python version:"
    python --version
    echo "----------------------"
    echo "Running airflow version:"
    airflow version
    echo "----------------------"
    airflow db init || exit $?

    airflow scheduler &
    SCHEDULER_PID="$!"
    airflow webserver
    kill "$SCHEDULER_PID"
else
    airflow "$@"
fi
