#!/usr/bin/env bash
command -v realpath >/dev/null
if [ ! $? ]; then
  # resolve for mac
  function realpath() {
    python3 -c "import os; print(os.path.realpath('$1'))"
  }
fi

: ${REPO_PATH:="$(dirname $(dirname $(realpath "$BASH_SOURCE[0]")))"}
export PYTHONPATH="$REPO_PATH"
export AIRFLOW_HOME="$REPO_PATH/tests"
SQLITE_DB_FILE="$REPO_PATH/tests/airflow.db"

echo "DB file: $SQLITE_DB_FILE"
export AIRFLOW__CORE__SQL_ALCHEMY_CONN="sqlite:///${SQLITE_DB_FILE}"
echo "ALCHEMY_CONN: $AIRFLOW__CORE__SQL_ALCHEMY_CONN"
airflow "$@"
