#!/usr/bin/env bash
if [ "$1" != "delete" ] && [ "$1" != "d" ]; then
    BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    : "${BRANCH:="master"}"
    echo "Applying changes on branch: $BRANCH"
    helmfile apply --set envs.ZAIRFLOW_GIT_AUTOSYNC_BRANCH=$BRANCH
else
    helmfile delete
fi
