#!/usr/bin/env bash
echo "Building the docker image.."
docker build -f ./Dockerfile ../.. -t kube_job_operator_tester

echo "Deploying helm.."
if [ "$1" != "delete" ] && [ "$1" != "-d" ]; then
    BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    : "${BRANCH:="master"}"
    echo "Applying changes on branch: $BRANCH"
    helmfile apply --set envs.ZAIRFLOW_GIT_AUTOSYNC_BRANCH=$BRANCH || exit $?
else
    helmfile delete || exit $?
fi
