#!/usr/bin/env bash
command -v realpath >/dev/null
if [ ! $? ]; then
  # resolve for mac
  function realpath() {
    python3 -c "import os; print(os.path.realpath('$1'))"
  }
fi

: ${REPO_PATH:="$(dirname $(dirname $(realpath "$BASH_SOURCE[0]")))"}
source "$REPO_PATH/test/manual/configure"
airflow "$@"
