#!/usr/bin/env bash
command -v realpath >/dev/null
if [ ! $? ]; then
  # resolve for mac
  function realpath() {
    python3 -c "import os; print(os.path.abspath('$1'))"
  }
fi

CUR_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
REPO_PATH="$(realpath "$CUR_DIR/../../")"

[ -f "$REPO_PATH/.env" ] && {
  source "$REPO_PATH/.env" || exit $?
}
source "$CUR_DIR/configure" || exit $?

if [ "$1" == "reset" ]; then
  rm -rf "$REPO_PATH/.local/airflow.db" && echo "deleted airflow db"
  rm -rf "$REPO_PATH/tests/local_airflow/airflow.cfg" && echo "deleted airflow config"
  shift
fi

if [ "$#" -eq 0 ]; then
  echo "----------------------"
  echo "Running python version:"
  python --version
  echo "----------------------"
  echo "Running airflow version:"
  airflow version
  echo "----------------------"
  airflow scheduler &
  SCHEDULER_PID="$!"
  airflow webserver
  kill "$SCHEDULER_PID"
else
  airflow "$@"
fi
