#!/usr/bin/env bash
command -v realpath >/dev/null
if [ ! $? ]; then
  # resolve for mac
  function realpath() {
    python3 -c "import os; print(os.path.abspath('$1'))"
  }
fi

CUR_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
REPO_PATH="$(realpath "$CUR_DIR/../../")"

source "$CUR_DIR/configure" || exit $?

if [ "$#" -eq 0 ]; then
  echo "----------------------"
  echo "Running python version:"
  python --version
  echo "----------------------"
  echo "Running airflow version:"
  airflow version
  echo "----------------------"
  airflow scheduler &
  SCHEDULER_PID="$!"
  airflow webserver
  kill "$SCHEDULER_PID"
else
  airflow "$@"
fi
