# the code in this file is augmented by an ejs template
# and by loading the yaml into memory.
# some of these values will be replaced.
apiVersion: batch/v1
kind: Job
metadata:
  name: '{name}'
  finalizers:
    - foregroundDeletion
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job-executor
          image: '{image}'
  backoffLimit: 0
